/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connect.connect;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author eduar
 */
public class tela_consulta_vendas extends javax.swing.JFrame {
    /**
     * Creates new form tela_consulta_vendas
     */
    public tela_consulta_vendas() {
        initComponents();
        inicio();
        inicio_tabela_prod();
        jPanel3.setVisible(false);
    }
Connection con = null; 




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_consultar = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        label_id_venda = new javax.swing.JLabel();
        label_consultar_nota_fiscal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELA = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_prod = new javax.swing.JTable();
        txt_cpf = new javax.swing.JLabel();
        txt_data = new javax.swing.JLabel();
        label_cpf = new javax.swing.JLabel();
        txt_total1 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        label_data = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 34, 34));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_consultar.setBackground(new java.awt.Color(255, 51, 0));
        btn_consultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 122, 30));

        txt_id.setBackground(new java.awt.Color(34, 34, 34));
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.setForeground(new java.awt.Color(255, 255, 255));
        txt_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 140, 30));

        label_id_venda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_id_venda.setForeground(new java.awt.Color(255, 255, 255));
        label_id_venda.setText("Id da venda:");
        jPanel1.add(label_id_venda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        label_consultar_nota_fiscal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_consultar_nota_fiscal.setForeground(new java.awt.Color(255, 255, 255));
        label_consultar_nota_fiscal.setText("Consultar nota fiscal");
        jPanel1.add(label_consultar_nota_fiscal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 820, 10));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("URPH STYLE");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoJava.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 120));

        jPanel3.setBackground(new java.awt.Color(34, 34, 34));

        TABELA.setBackground(new java.awt.Color(34, 34, 34));
        TABELA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TABELA.setForeground(new java.awt.Color(255, 255, 255));
        TABELA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TABELA);

        tabela_prod.setBackground(new java.awt.Color(34, 34, 34));
        tabela_prod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabela_prod.setForeground(new java.awt.Color(255, 255, 255));
        tabela_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabela_prod);

        txt_cpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cpf.setForeground(new java.awt.Color(255, 255, 255));
        txt_cpf.setText("CPF:");

        txt_data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_data.setForeground(new java.awt.Color(255, 255, 255));
        txt_data.setText("DATA:");

        label_cpf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_cpf.setForeground(new java.awt.Color(255, 255, 255));

        txt_total1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_total1.setForeground(new java.awt.Color(255, 255, 255));
        txt_total1.setText("Total:");

        txt_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_total.setForeground(new java.awt.Color(255, 255, 255));

        label_data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_data.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_data, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(363, 363, 363)
                        .addComponent(txt_total1)
                        .addGap(14, 14, 14)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_data)
                            .addComponent(label_data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_total1)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 273, 810, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
       inicio();
       inicio_tabela_prod();    
       
        try
        {
        con = new connect().getConnection();
        String sql = "SELECT * FROM java_vendas WHERE id_vendas = '"+txt_id.getText()+"' ";
      PreparedStatement stmt = con.prepareStatement(sql);
      ResultSet resultado = stmt.executeQuery(sql);
      if(!resultado.next())
      {
         JOptionPane.showMessageDialog(null,"Erro, essa venda não existe!");
         System.exit(0);
      }
      else
      {
            
          
              String cpf = (resultado.getString("cpf_cliente"));
              System.out.println("cpf "+cpf);
              label_cpf.setText(cpf);
              String sql_produto_itens = "SELECT id_produto,unidades,valor_unidade,valor_total FROM java_itens_venda WHERE id_venda = '"+txt_id.getText()+"'";
              PreparedStatement stmt2 = con.prepareStatement(sql_produto_itens);
              ResultSet resultado2 = stmt2.executeQuery(sql_produto_itens);
              
              
              
              
              System.out.println("Resultado 2 "+resultado2.first());
              String sql_cliente = "SELECT nome FROM java_clientes WHERE cpf = '"+cpf+"'";
              PreparedStatement stmt3 = con.prepareStatement(sql_cliente);
              ResultSet resultado3 = stmt3.executeQuery(sql_cliente);

              
           
 
                ResultSetMetaData metaData = resultado2.getMetaData();
                       int numeroDeColunas = metaData.getColumnCount(); 
                    
                       int cada_item = 1;
                       
                        
                  
                           
                       
                       
                            do
                            {
                               Object [] rowData = new Object[numeroDeColunas];
                               System.out.println("aa "+rowData.length);
                                  for (int i = 0; i < rowData.length; i++)
                                  {
                                      rowData[i] = resultado2.getObject(i+1);
                                      
                                  }
                          System.out.println("id prod "+rowData[0]);
                          String sql_produto = "SELECT nome,descricao,tamanho FROM java_produtos WHERE id_produto = '"+rowData[0]+"'";
                          PreparedStatement stmt4 = con.prepareStatement(sql_produto);
                          ResultSet resultado4 = stmt4.executeQuery(sql_produto);
                          
                          String dados[] = new String[3];
                          if(resultado4.next())
                          {
                            do
                            {
                            dados[0] = resultado4.getString("nome");
                            dados[1] = resultado4.getString("descricao");
                            dados[2] = resultado4.getString("tamanho");
                            }
                            while(resultado4.next());
                          }
                          
                          DefaultTableModel model_prod = (DefaultTableModel) tabela_prod.getModel(); 
                          model_prod.addRow(dados);
                          
                          DefaultTableModel model = (DefaultTableModel) TABELA.getModel();  
                          model.addRow(rowData);
                          System.out.println(Arrays.toString(rowData));
                          TABELA.getColumnModel().getColumn(0).setPreferredWidth(20);
                          TABELA.getColumnModel().getColumn(1).setPreferredWidth(35);
                          
                          TABELA.setModel(model);
                               System.out.println("VALORES: "+resultado2.getString("id_produto"));
                               cada_item++; 
                            }   
                            while(resultado2.next());
                            
                            
                            jPanel3.setVisible(true);
                            
    int linhas_carrinho = TABELA.getModel().getRowCount();
    float total = 0;
    

        
        
    for(int abc=0;abc<linhas_carrinho;abc++)
    {
        total += (Float.parseFloat((TABELA.getValueAt(abc,3).toString())));
    }

    txt_total.setText("R$:"+total);
    String data = resultado.getString("data");
          System.out.println("Data:" +data);
    label_data.setText(data);

              
             
      }
      
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(tela_consulta_vendas.class.getName()).log(Level.SEVERE, null, ex);
        }           
    }//GEN-LAST:event_btn_consultarActionPerformed

    
    
    
    public void inicio()
    {
            

        
    DefaultTableModel model = new DefaultTableModel(null,new String[]{"Id", "Unidades","Preço Unitário", "Total"})
{
     @Override
        public boolean isCellEditable(int row, int col)
    {
    return false;
    }
};
    
    DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
headerRenderer.setBackground(new Color(34, 34, 34));

for (int i = 0; i < TABELA.getModel().getColumnCount(); i++) {
        TABELA.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
}
    TABELA.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
    
    TABELA.getParent().setBackground(new Color(34,34,34));
    TABELA.setModel(model); 
    
    
    }
    
        private void inicio_tabela_prod()
    {
        
    DefaultTableModel model = new DefaultTableModel(null,new String[]{"Nome", "Descrição", "Tamanho"})
{
     @Override
        public boolean isCellEditable(int row, int col)
    {
    return false;
    }
};
    DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
headerRenderer.setBackground(Color.YELLOW);

for (int i = 0; i < tabela_prod.getModel().getColumnCount(); i++) {
    tabela_prod.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
}
    
    tabela_prod.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
   
    tabela_prod.getParent().setBackground(new Color(34,34,34));
    tabela_prod.setModel(model); 
    }
    

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_consulta_vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_consulta_vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_consulta_vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_consulta_vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_consulta_vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABELA;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_consultar_nota_fiscal;
    private javax.swing.JLabel label_cpf;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_id_venda;
    private javax.swing.JTable tabela_prod;
    private javax.swing.JLabel txt_cpf;
    private javax.swing.JLabel txt_data;
    private javax.swing.JTextField txt_id;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_total1;
    // End of variables declaration//GEN-END:variables
}
