/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eduar
 */
public class tela_principal extends javax.swing.JFrame {
private tela_cadastro_clientes tela_cliente = null;
private tela_cadastro_produtos tela_produto = null;
private tela_consulta_cliente tela_consulta_cliente = null;
private tela_consulta_produto tela_consulta_produto = null;
private autores autores = null;
private tela_consulta_vendas tela_vendas = null;
private tela_venda vendas = null;
    /**
     * Creates new form tela_principal
     */
    public tela_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_cadastro_clientes = new javax.swing.JMenuItem();
        btn_cadastro_produto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btn_consultar_clientes = new javax.swing.JMenuItem();
        btn_consultar_produtos = new javax.swing.JMenuItem();
        btn_consultar_vendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btn_vendas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btn_autores = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja Berg & Borba");
        setLocation(new java.awt.Point(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoJavaMaior.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("URPH STYLE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1080, 530));

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenu1.setForeground(new java.awt.Color(255, 102, 0));
        jMenu1.setText("Cadastro");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_cadastro_clientes.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadastro_clientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cadastro_clientes.setText("Cadastro Cliente");
        btn_cadastro_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_clientesActionPerformed(evt);
            }
        });
        jMenu1.add(btn_cadastro_clientes);

        btn_cadastro_produto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cadastro_produto.setText("Cadastro Produto");
        btn_cadastro_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_produtoActionPerformed(evt);
            }
        });
        jMenu1.add(btn_cadastro_produto);

        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 102, 0));
        jMenu3.setText("Consulta");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_consultar_clientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_consultar_clientes.setText("Consultar Clientes");
        btn_consultar_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_clientesActionPerformed(evt);
            }
        });
        jMenu3.add(btn_consultar_clientes);

        btn_consultar_produtos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_consultar_produtos.setText("Consultar Produtos");
        btn_consultar_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_produtosActionPerformed(evt);
            }
        });
        jMenu3.add(btn_consultar_produtos);

        btn_consultar_vendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_consultar_vendas.setText("Consultar Nota Fiscal");
        btn_consultar_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_vendasActionPerformed(evt);
            }
        });
        jMenu3.add(btn_consultar_vendas);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(255, 102, 0));
        jMenu4.setText("Loja");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_vendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_vendas.setText("Comprar");
        btn_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vendasActionPerformed(evt);
            }
        });
        jMenu4.add(btn_vendas);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(255, 102, 0));
        jMenu5.setForeground(new java.awt.Color(255, 102, 0));
        jMenu5.setText("Sobre");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btn_autores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_autores.setText("Autores");
        btn_autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_autoresActionPerformed(evt);
            }
        });
        jMenu5.add(btn_autores);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastro_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_clientesActionPerformed
              if(tela_cliente == null)
        {
            tela_cliente = new tela_cadastro_clientes();
            tela_cliente.setVisible(true);
        }
        else
            tela_cliente.setVisible(true);
    }//GEN-LAST:event_btn_cadastro_clientesActionPerformed

    private void btn_consultar_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_clientesActionPerformed
           if(tela_consulta_cliente == null)
        {
            tela_consulta_cliente = new tela_consulta_cliente();
            tela_consulta_cliente.setVisible(true);
        }
        else
            tela_consulta_cliente.setVisible(true);
    }//GEN-LAST:event_btn_consultar_clientesActionPerformed

    private void btn_cadastro_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_produtoActionPerformed
        if(tela_produto == null)
        {
            tela_produto = new tela_cadastro_produtos();
            tela_produto.setVisible(true);
        }
        else
            tela_produto.setVisible(true);
    }//GEN-LAST:event_btn_cadastro_produtoActionPerformed

    private void btn_autoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_autoresActionPerformed
        if(autores == null)
        {
            autores = new autores();
            autores.setVisible(true);
        }
        else
            autores.setVisible(true);    
    }//GEN-LAST:event_btn_autoresActionPerformed

    private void btn_consultar_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_produtosActionPerformed
       
            if(tela_consulta_produto == null)
            {
                try { 
                    tela_consulta_produto = new tela_consulta_produto();
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(tela_principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                tela_consulta_produto.setVisible(true);
            }
            else
                tela_consulta_produto.setVisible(true);
            ;

    }//GEN-LAST:event_btn_consultar_produtosActionPerformed

    private void btn_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vendasActionPerformed
        tela_venda venda = new tela_venda();
        
        venda.setVisible(true);
    }//GEN-LAST:event_btn_vendasActionPerformed

    private void btn_consultar_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_vendasActionPerformed
        if(tela_vendas==null)
        {
            tela_vendas = new tela_consulta_vendas();
            tela_vendas.setVisible(true);
        }
        else
            tela_vendas.setVisible(true);
    }//GEN-LAST:event_btn_consultar_vendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tela_principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_autores;
    private javax.swing.JMenuItem btn_cadastro_clientes;
    private javax.swing.JMenuItem btn_cadastro_produto;
    private javax.swing.JMenuItem btn_consultar_clientes;
    private javax.swing.JMenuItem btn_consultar_produtos;
    private javax.swing.JMenuItem btn_consultar_vendas;
    private javax.swing.JMenuItem btn_vendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
